/** Catálogo de telas — cada entrada gera <section>/<name>-<locale>.webp. */
export const SCREENS = [
  {
    name: 'scheduling-today',
    section: 'scheduling',
    url: '/dashboard/scheduling',
    settleMs: 2500,
    waitCount: { sel: 'main .MuiCard-root', min: 2 },
    // 1 = card "Próximo atendimento" · 2 = botão Novo agendamento
    highlights: [
      { selector: 'main .MuiCard-root', nth: 0, badge: 1 },
      { selector: 'main .MuiButton-contained', nth: 0, badge: 2 },
    ],
  },
  {
    name: 'scheduling-earnings',
    section: 'scheduling',
    url: '/dashboard/scheduling',
    steps: [{ waitMs: 2000 }, { clickRole: { role: 'tab', nth: 2 } }, { waitMs: 2500 }],
    waitCount: { sel: 'main .MuiCard-root', min: 5 },
    // 1 = cards de totais · 2 = gráfico diário
    highlights: [
      { selector: 'main .MuiGrid-container', nth: 0, badge: 1 },
      { selector: 'main .MuiCard-root', nth: 4, badge: 2 },
    ],
  },
  {
    name: 'scheduling-services',
    section: 'scheduling',
    url: '/dashboard/scheduling',
    steps: [{ waitMs: 2000 }, { clickRole: { role: 'tab', nth: 3 } }, { waitMs: 1800 }],
    waitCount: { sel: 'main .MuiCard-root', min: 5 },
    // Card do serviço (toggle + editar + excluir)
    highlights: [{ selector: 'main .MuiCard-root', nth: 0 }],
  },
  {
    name: 'my-linkzee',
    section: 'your-page',
    url: '/dashboard/links',
    settleMs: 2500,
    // Botão "+ Adicionar" — o coração da página
    highlights: [{ selector: 'main .MuiButton-contained', nth: 0 }],
  },
  {
    name: 'public-bio',
    section: 'your-page',
    url: '/{slug}',
    auth: false,
    viewport: { width: 390, height: 844 },
    settleMs: 2500,
    highlights: [],
  },
  {
    name: 'booking-wizard',
    section: 'scheduling',
    url: '/{slug}?agenda=1',
    auth: false,
    viewport: { width: 390, height: 844 },
    // 1º card de serviço por ESTRUTURA (o nome muda por idioma — clickText quebrava)
    steps: [{ waitMs: 1800 }, { clickSel: 'div[role=dialog] button.p-4[class*=ring-1]' }, { waitMs: 1800 }],
    highlights: [],
  },
  {
    name: 'design-themes',
    section: 'design',
    url: '/dashboard/design',
    settleMs: 2500,
    highlights: [],
  },
  {
    name: 'performance',
    section: 'analytics',
    url: '/dashboard/performance',
    settleMs: 3000,
    highlights: [],
  },
  {
    name: 'scheduling-settings',
    section: 'scheduling',
    url: '/dashboard/scheduling',
    steps: [{ waitMs: 2000 }, { clickRole: { role: 'tab', nth: 4 } }, { waitMs: 2200 }],
    waitCount: { sel: 'main .MuiCard-root', min: 3 },
    highlights: [],
  },
  {
    name: 'booking-wizard-services',
    section: 'scheduling',
    url: '/{slug}?agenda=1',
    auth: false,
    viewport: { width: 390, height: 844 },
    settleMs: 2600,
    highlights: [],
  },
  {
    name: 'products',
    section: 'products',
    url: '/dashboard/products',
    settleMs: 2600,
    highlights: [],
  },
  {
    name: 'analytics',
    section: 'analytics',
    url: '/dashboard/analytics',
    settleMs: 3200,
    highlights: [],
  },
  {
    name: 'plan',
    section: 'billing',
    url: '/dashboard/plan',
    settleMs: 2600,
    highlights: [],
  },
  {
    name: 'settings',
    section: 'account',
    url: '/dashboard/settings',
    settleMs: 2400,
    highlights: [],
  },
  /* ---------------- Onda A ---------------- */
  {
    name: 'add-item-modal',
    section: 'your-page',
    url: '/dashboard/links',
    steps: [{ waitMs: 2500 }, { clickSel: 'main .MuiButton-contained' }, { waitMs: 1400 }],
    highlights: [],
  },
  {
    name: 'product-edit-modal',
    section: 'products',
    url: '/dashboard/products',
    steps: [{ waitMs: 2600 }, { clickSel: 'main .MuiCard-root .MuiIconButton-root' }, { waitMs: 1600 }],
    highlights: [],
  },
  {
    name: 'product-edit-offer',
    section: 'products',
    url: '/dashboard/products',
    steps: [
      { waitMs: 2600 },
      { clickSel: 'main .MuiCard-root .MuiIconButton-root' },
      { waitMs: 1600 },
      { eval: "const el=document.querySelector('[role=dialog] .MuiDialogContent-root'); if(el) el.scrollTop = el.scrollHeight;" },
      { waitMs: 600 },
    ],
    highlights: [],
  },
  {
    name: 'profile-header',
    section: 'your-page',
    url: '/dashboard/header',
    settleMs: 2600,
    highlights: [],
  },
  {
    name: 'collections',
    section: 'your-page',
    url: '/dashboard/links',
    settleMs: 2600,
    steps: [{ eval: 'window.scrollBy(0, 500)' }, { waitMs: 400 }],
    highlights: [],
  },
  {
    name: 'qr-dialog',
    section: 'your-page',
    url: '/dashboard/links',
    steps: [{ waitMs: 2500 }, { clickSel: '.MuiIconButton-root', nth: 2 }, { waitMs: 1600 }],
    highlights: [],
  },
  {
    name: 'public-bio-tips',
    section: 'your-page',
    url: '/{slug}',
    auth: false,
    viewport: { width: 390, height: 844 },
    settleMs: 2600,
    steps: [{ eval: 'window.scrollTo(0, document.body.scrollHeight)' }, { waitMs: 800 }],
    highlights: [],
  },
  {
    name: 'agenda-hours',
    section: 'scheduling',
    url: '/dashboard/scheduling',
    steps: [{ waitMs: 2000 }, { clickRole: { role: 'tab', nth: 4 } }, { waitMs: 2200 }, { scrollToNth: { sel: 'main .MuiCard-root', nth: 5 } }, { waitMs: 400 }],
    waitCount: { sel: 'main .MuiCard-root', min: 8 },
    highlights: [{ selector: 'main .MuiCard-root', nth: 5 }],
  },
  {
    name: 'agenda-blocks',
    section: 'scheduling',
    url: '/dashboard/scheduling',
    steps: [{ waitMs: 2000 }, { clickRole: { role: 'tab', nth: 4 } }, { waitMs: 2200 }, { scrollToNth: { sel: 'main .MuiCard-root', nth: 7 } }, { waitMs: 400 }],
    waitCount: { sel: 'main .MuiCard-root', min: 8 },
    highlights: [{ selector: 'main .MuiCard-root', nth: 7 }],
  },
  {
    name: 'agenda-confirm',
    section: 'scheduling',
    url: '/dashboard/scheduling',
    steps: [{ waitMs: 2000 }, { clickRole: { role: 'tab', nth: 4 } }, { waitMs: 2200 }, { scrollToNth: { sel: 'main .MuiCard-root', nth: 8 } }, { waitMs: 400 }],
    waitCount: { sel: 'main .MuiCard-root', min: 8 },
    highlights: [{ selector: 'main .MuiCard-root', nth: 8 }],
  },
  {
    name: 'categories',
    section: 'products',
    url: '/dashboard/categories',
    settleMs: 2600,
    highlights: [],
  },
  {
    name: 'design-colors',
    section: 'design',
    url: '/dashboard/design',
    steps: [{ waitMs: 2500 }, { clickSel: 'main .MuiButtonBase-root', nth: 5 }, { waitMs: 1500 }],
    highlights: [],
  },
  /* ---------------- Onda E ---------------- */
  {
    name: 'settings-security',
    section: 'account',
    url: '/dashboard/settings',
    steps: [{ waitMs: 2200 }, { clickRole: { role: 'tab', nth: 1 } }, { waitMs: 1800 }],
    highlights: [],
  },
  {
    name: 'settings-notifications',
    section: 'account',
    url: '/dashboard/settings',
    steps: [{ waitMs: 2200 }, { clickRole: { role: 'tab', nth: 2 } }, { waitMs: 1800 }],
    highlights: [],
  },
  {
    name: 'settings-integrations',
    section: 'account',
    url: '/dashboard/settings',
    steps: [{ waitMs: 2200 }, { clickRole: { role: 'tab', nth: 4 } }, { waitMs: 1800 }],
    highlights: [],
  },
  /* ---------------- Onda B ---------------- */
  {
    name: 'manage-page',
    section: 'scheduling',
    url: '/a/manage/{slug}/{manageToken}',
    auth: false,
    viewport: { width: 390, height: 844 },
    settleMs: 2600,
    highlights: [],
  },
  {
    name: 'confirm-page',
    section: 'scheduling',
    url: '/a/confirm/{slug}/{confirmToken}',
    auth: false,
    viewport: { width: 390, height: 844 },
    settleMs: 2600,
    highlights: [],
  },
  {
    name: 'booking-wizard-waitlist',
    section: 'scheduling',
    url: '/{slug}?agenda=1',
    auth: false,
    viewport: { width: 390, height: 844 },
    // Slots do dia MOCKADOS vazios (estado real de "sem horários" + CTA da
    // fila; reproduzir ao vivo exigiria lotar 14 dias). O 🔔 abre o formulário.
    routes: [
      {
        pattern: '**detail=slots**',
        json: { error: false, message: 'ok', data: { slots: [], timezone: 'America/Sao_Paulo' } },
      },
    ],
    steps: [
      { waitMs: 2000 },
      { clickSel: 'div[role=dialog] button.p-4[class*=ring-1]', nth: 2 },
      { waitMs: 2000 },
      { clickText: '🔔' },
      { waitMs: 1200 },
    ],
    highlights: [],
  },
  /* ---------------- Onda D ---------------- */
  {
    name: 'ai-assistant',
    section: 'ai-assistant',
    url: '/dashboard/ai-assistant',
    settleMs: 5000,
    highlights: [],
  },
  {
    name: 'ai-assistant-knowledge',
    section: 'ai-assistant',
    url: '/dashboard/ai-assistant',
    steps: [
      { waitMs: 2800 },
      { clickRole: { role: 'tab', nth: 1 } },
      { waitMs: 1800 },
      { eval: "[...document.querySelectorAll('main .MuiCard-root')].find((c) => c.textContent.includes('PDF'))?.scrollIntoView({ block: 'center' })" },
      { waitMs: 500 },
    ],
    highlights: [],
  },
  {
    name: 'ai-assistant-leads',
    section: 'ai-assistant',
    url: '/dashboard/ai-assistant',
    steps: [{ waitMs: 2800 }, { clickRole: { role: 'tab', nth: 2 } }, { waitMs: 1800 }],
    highlights: [],
  },
  {
    name: 'anna-widget',
    section: 'ai-assistant',
    url: '/{slug}',
    auth: false,
    viewport: { width: 390, height: 844 },
    // Botão do assistente dentro do campo de busca (Spotlight) → abre o chat
    // com a saudação (texto estático do item — determinístico). waitMs antes
    // do clique: hidratação (clicar cedo demais não dispara o handler).
    steps: [{ waitMs: 2600 }, { clickSel: 'button[class*="right-1.5"]' }, { waitMs: 2800 }],
    highlights: [],
  },
  {
    name: 'zee-idle',
    section: 'zee',
    url: '/dashboard/links',
    // aria-label começa com "Zee" nos 5 idiomas (clickText casava com o logo).
    steps: [{ waitMs: 2500 }, { clickSel: 'button[aria-label^="Zee"]' }, { waitMs: 3500 }],
    highlights: [],
  },
  /* ---------------- Onda C (modo equipe — setup/teardown manual) ---------------- */
  {
    name: 'agenda-team',
    section: 'scheduling',
    url: '/dashboard/scheduling',
    steps: [{ waitMs: 2200 }, { clickRole: { role: 'tab', nth: 4 } }, { waitMs: 2000 }],
    highlights: [],
  },
  {
    name: 'booking-wizard-staff',
    section: 'scheduling',
    url: '/{slug}?agenda=1',
    auth: false,
    viewport: { width: 390, height: 844 },
    // Serviço compartilhado (Design de Sobrancelha, nth 3) → passo Profissional
    // com as duas profissionais + "qualquer".
    steps: [
      { waitMs: 2000 },
      { clickSel: 'div[role=dialog] button.p-4[class*=ring-1]', nth: 3 },
      { waitMs: 2000 },
    ],
    highlights: [],
  },
];
